# Generated by Django 5.0.6 on 2024-06-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('cad_number', models.CharField(help_text='Максимальная длина кадастрового номера не должна превышать 16 знаков', max_length=16, unique=True, verbose_name='Кадастровый номер')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='41.385064', max_digits=10, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='-2.173403', max_digits=10, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('response', models.CharField(choices=[('true', 'Положительный ответ'), ('false', 'Отрицательный ответ'), ('n/a', 'Нет данных')], default='n/a', max_length=5, verbose_name='Ответ')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_address', to='app_geo.address')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
